# Generated by Django 6.0.2 on 2026-02-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItcHsMaster',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('hs_code', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('policy', models.TextField(blank=True, null=True)),
                ('policy_conditions', models.TextField(blank=True, null=True)),
                ('schedule_type', models.CharField(max_length=10)),
                ('chapter_num', models.IntegerField(null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('parent_hs_code', models.CharField(blank=True, max_length=10, null=True)),
                ('hs_level', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'itc_hs_master',
                'managed': False,
            },
        ),
    ]
